<?php
declare(strict_types=1);

// PHPUnit\Framework\TestCase comes from the vendor/autoload.php generated by Composer
use PHPUnit\Framework\TestCase;

final class CsrfHelperTest extends TestCase
{
    public static function setUpBeforeClass(): void
    {
        // Ensure a fresh session
        if (session_status() === PHP_SESSION_NONE) {
            session_start();
        }
        $_SESSION = [];

        // Include the CSRF helper itself (adjust path if needed)
        require_once __DIR__ . '/../config/helpers/csrf.php';
    }

    protected function tearDown(): void
    {
        // Clear session after each test so tests remain independent
        $_SESSION = [];
    }

    public function testGenerateReturnsSixtyFourHexChars(): void
    {
        $token = generate_csrf_token();
        // It must be a 64-character hex string (32 bytes in hex)
        $this->assertIsString($token);
        $this->assertMatchesRegularExpression('/^[0-9a-f]{64}$/', $token);
        // Re‐calling generate_csrf_token() should give exactly the same token
        $token2 = generate_csrf_token();
        $this->assertSame($token, $token2);
    }

    public function testVerifyFailsIfNoSessionToken(): void
    {
        // If session has no csrf_token, any input should return false
        $this->assertFalse(verify_csrf_token('whatever'));
    }

    public function testVerifySucceedsAndInvalidatesSession(): void
    {
        // 1) Generate a token and check it is stored in $_SESSION
        $expected = generate_csrf_token();
        $this->assertArrayHasKey('csrf_token', $_SESSION);
        $this->assertSame($expected, $_SESSION['csrf_token']);

        // 2) Passing the correct token should return true
        $this->assertTrue(verify_csrf_token($expected));

        // 3) After a successful verify, the session entry must be removed (invalidated)
        $this->assertArrayNotHasKey('csrf_token', $_SESSION);
    }

    public function testVerifyFailsWhenTokenDoesNotMatch(): void
    {
        // Manually set a known value in session
        $known = str_repeat('a', 64);
        $_SESSION['csrf_token'] = $known;

        // Use a different string of correct length
        $wrong = str_repeat('b', 64);
        $this->assertFalse(verify_csrf_token($wrong));

        // Because it was wrong, the session key should still remain unchanged
        $this->assertSame($known, $_SESSION['csrf_token']);
    }
}
